# For more information: https://laravel.com/docs/sail
version: '3'
services:
    app:
        container_name: decor.app
        build:
            context: ./vendor/laravel/sail/runtimes/8.0
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.0/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
        environment:
            WWWUSER: '${WWWUSER}'

            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - mysql
            - redis
            - meilisearch
    mysql:
        container_name: decor.mysql
        image: 'mysql:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3388}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'sailmysql:/var/lib/mysql'
        networks:
            - sail
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
            retries: 3
            timeout: 5s
    redis:
        container_name: decor.redis
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6399}:6379'
        volumes:
            - 'sailredis:/data'
        networks:
            - sail
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]
            retries: 3
            timeout: 5s
    meilisearch:
        container_name: decor.meilisearch
        image: 'getmeili/meilisearch:latest'
        ports:
            - '7700:7700'
        expose:
            -   7700
        volumes:
            - 'sailmeilisearch:/data.ms'
        networks:
            - sail
        environment:
            MEILI_MASTER_KEY: Some-master-key-123
        healthcheck:
            test: [ "CMD", "wget", "--no-verbose", "--spider",  "http://localhost:7700/health" ]
            retries: 3
            timeout: 5s
    mailhog:
        container_name: decor.mailhog
        image: 'mailhog/mailhog:latest'
        ports:
            - '${FORWARD_MAILHOG_PORT:-1025}:1025'
            - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
        networks:
            - sail

    phpmyadmin:
        container_name: decor.phpmyadmin
        image: phpmyadmin
        networks:
            - sail
        environment:
            PMA_ARBITRARY: 1
            PMA_HOST: '${DB_HOST}'
            PMA_USER: '${DB_USERNAME}'
            PMA_PASSWORD: '${DB_PASSWORD}'
        ports:
            - "1111:80"

    cloudsql:
        image: gcr.io/cloudsql-docker/gce-proxy:1.12
        volumes:
            - ./gce.json:/config
        entrypoint:
            - /cloud_sql_proxy
            - -instances=nth-micron-344820:us-central1:nostashteeb=tcp:0.0.0.0:3306
            - -credential_file=/config

    phpmyadmin-prod:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin-prod
        environment:
            PMA_HOST: cloudsql
            PMA_USER: '${REMOTE_DB_USERNAME}'
            PMA_PASSWORD: '${REMOTE_DB_PASSWORD}'
        ports:
            - "1112:80"
networks:
    sail:
        driver: bridge
volumes:
    sailmysql:
        driver: local
    sailredis:
        driver: local
    sailmeilisearch:
        driver: local
